export interface Category {
  id: number;
  enabled: boolean;
  name: string;
  nameTranslated: string;
  parentId?: number;
}

export interface ProductOptionChoice {
  text: string;
  textTranslated: Record<string, string>;
  priceModifier: number;
  priceModifierType: string;
}

export interface ProductOption {
  type: string;
  name: string;
  nameTranslated: Record<string, string>;
  choices: ProductOptionChoice[];
  defaultChoice: number;
  required: boolean;
}

export interface Tax {
  taxable: boolean;
  defaultLocationIncludedTaxRate: number;
  enabledManualTaxes: any[];
  taxClassCode: string;
}

export interface LowestPriceSettings {
  lowestPriceEnabled: boolean;
}

export interface Shipping {
  type: string;
  methodMarkup: number;
  flatRate: number;
  disabledMethods: any[];
  enabledMethods: any[];
}

export interface ImageInfo {
  url: string;
  width: number;
  height: number;
}

export interface ColorInfo {
  red: number;
  green: number;
  blue: number;
  alpha: number;
}

export interface BorderInfo {
  dominatingColor: ColorInfo;
  homogeneity: boolean;
}

export interface GalleryImage {
  id: number;
  url: string;
  thumbnail: string;
  originalImageUrl: string;
  imageUrl: string;
  hdThumbnailUrl: string;
  thumbnailUrl: string;
  smallThumbnailUrl: string;
  width: number;
  height: number;
  orderBy: number;
  borderInfo: BorderInfo;
}

export interface MediaImage {
  id: string;
  isMain: boolean;
  orderBy: number;
  image160pxUrl: string;
  image400pxUrl: string;
  image800pxUrl: string;
  image1500pxUrl: string;
  imageOriginalUrl: string;
}

export interface Media {
  images: MediaImage[];
  videos: any[];
}

export interface RelatedCategory {
  enabled: boolean;
  categoryId: number;
  productCount: number;
}

export interface RelatedProducts {
  productIds: number[];
  relatedCategory: RelatedCategory;
}

export interface Product {
  id: number;
  sku: string;
  thumbnailUrl: string;
  unlimited: boolean;
  inStock: boolean;
  name: string;
  price: number;
  priceInProductList: number;
  defaultDisplayedPrice: number;
  defaultDisplayedPriceFormatted: string;
  tax: Tax;
  lowestPrice: number;
  defaultDisplayedLowestPrice: number;
  defaultDisplayedLowestPriceFormatted: string;
  lowestPriceSettings: LowestPriceSettings;
  isShippingRequired: boolean;
  hasFreeShipping: boolean;
  weight: number;
  url: string;
  autogeneratedSlug: string;
  customSlug: string;
  created: string;
  updated: string;
  createTimestamp: number;
  updateTimestamp: number;
  productClassId: number;
  enabled: boolean;
  options: ProductOption[];
  fixedShippingRateOnly: boolean;
  fixedShippingRate: number;
  shipping: Shipping;
  defaultCombinationId: number;
  imageUrl: string;
  smallThumbnailUrl: string;
  hdThumbnailUrl: string;
  originalImageUrl: string;
  originalImage: ImageInfo;
  borderInfo: BorderInfo;
  description: string;
  galleryImages: GalleryImage[];
  media: Media;
  categoryIds: number[];
  categories: Category[];
  defaultCategoryId: number;
  seoTitle: string;
  seoDescription: string;
  attributes: any[];
  relatedProducts: RelatedProducts;
  combinations: any[];
  volume: number;
  showOnFrontpage: number;
  isSampleProduct: boolean;
  googleItemCondition: string;
  isGiftCard: boolean;
  discountsAllowed: boolean;
  nameYourPriceEnabled: boolean;
  compositeComponents: any[];
  compositeParents: any[];
}

export interface PaginatedResponse<T> {
  total: number;
  count: number;
  offset: number;
  limit: number;
  items: T[];
}
